const themes = {
    default_theme: 'system',
    default_light_theme: 'tomorrow',
    default_dark_theme: 'tomorrow_night',
    themes: [
        {
            name: 'system',
            label: 'System (follow OS)',
            class: 'system',
            type: 'system',
        },
        {
            name: 'chaos',
            label: 'Chaos (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'chrome',
            label: 'Chrome (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'cloud9_day',
            label: 'Cloud9 day (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'cloud9_night',
            label: 'Cloud9 night (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'clouds',
            label: 'Clouds (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'crimson_editor',
            label: 'Crimson editor (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'dracula',
            label: 'Dracula (dark)',
            class: 'dark-lighter',
            type: 'dark',
        },
        {
            name: 'eclipse',
            label: 'Eclipse (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'github',
            label: 'Github (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'github_dark',
            label: 'Github dark (dark)',
            class: 'dark-lighter',
            type: 'dark',
        },
        {
            name: 'idle_fingers',
            label: 'Idle fingers (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'iplastic',
            label: 'Iplastic (light)',
            class: 'light',
        },
        {
            name: 'kr_theme',
            label: 'Kr theme (dark)',
            class: 'dark-black',
            type: 'dark',
        },
        {
            name: 'merbivore_soft',
            label: 'Merbivore soft (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'merbivore',
            label: 'Merbivore (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'mono_industrial',
            label: 'Mono industrial (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'monokai',
            label: 'Monokai (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'nord_dark',
            label: 'Nord dark (dark)',
            class: 'dark-lighter',
            type: 'dark',
        },
        {
            name: 'solarized_light',
            label: 'Solarized light (light)',
            class: 'solarized-light',
            type: 'light',
        },
        {
            name: 'solarized_dark',
            label: 'Solarized dark (dark)',
            class: 'solarized-dark',
            type: 'dark',
        },
        {
            name: 'textmate',
            label: 'Textmate (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'tomorrow',
            label: 'Tomorrow (light)',
            class: 'light',
            type: 'light',
        },
        {
            name: 'tomorrow_night_bright',
            label: 'Tomorrow night bright (dark)',
            class: 'dark-black',
            type: 'dark',
        },
        {
            name: 'tomorrow_night',
            label: 'Tomorrow night (dark)',
            class: 'dark-lighter',
            type: 'dark',
        },
        {
            name: 'twilight',
            label: 'Twilight (dark)',
            class: 'dark-darker',
            type: 'dark',
        },
        {
            name: 'xcode',
            label: 'Xcode (light)',
            class: 'light',
            type: 'light',
        },
    ],
};

export default themes;
