
export default function Ascii() {
    return (
        <div className="ascii">
            <table className="asciiTable">
                <thead>
                    <tr>
                        <th>DEC</th>
                        <th>HEX</th>
                        <th>Symbol</th>
                        <th>CTRL-char</th>
                        <th>Description</th>
                        <th></th>
                        <th>DEC</th>
                        <th>HEX</th>
                        <th>Char</th>
                        <th></th>
                        <th>DEC</th>
                        <th>HEX</th>
                        <th>Char</th>
                        <th></th>
                        <th>DEC</th>
                        <th>HEX</th>
                        <th>Char</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>0</td>
                        <td>00</td>
                        <td>NUL</td>
                        <td>CTRL-&#64;</td>
                        <td>Null character</td>
                        <td></td>
                        <td>32</td>
                        <td>20</td>
                        <td>Space</td>
                        <td></td>
                        <td>64</td>
                        <td>40</td>
                        <td>&#64;</td>
                        <td></td>
                        <td>96</td>
                        <td>60</td>
                        <td>&#96;</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>01</td>
                        <td>SOH</td>
                        <td>CTRL-A</td>
                        <td>Start of Heading</td>
                        <td></td>
                        <td>33</td>
                        <td>21</td>
                        <td>&#33;</td>
                        <td></td>
                        <td>65</td>
                        <td>41</td>
                        <td>A</td>
                        <td></td>
                        <td>97</td>
                        <td>61</td>
                        <td>a</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>02</td>
                        <td>STX</td>
                        <td>CTRL-B</td>
                        <td>Start of Text</td>
                        <td></td>
                        <td>34</td>
                        <td>22</td>
                        <td>&quot;</td>
                        <td></td>
                        <td>66</td>
                        <td>42</td>
                        <td>B</td>
                        <td></td>
                        <td>98</td>
                        <td>62</td>
                        <td>b</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>03</td>
                        <td>ETX</td>
                        <td>CTRL-C</td>
                        <td>End of Text</td>
                        <td></td>
                        <td>35</td>
                        <td>23</td>
                        <td>&#35;</td>
                        <td></td>
                        <td>67</td>
                        <td>43</td>
                        <td>C</td>
                        <td></td>
                        <td>99</td>
                        <td>63</td>
                        <td>c</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>04</td>
                        <td>EOT</td>
                        <td>CTRL-D</td>
                        <td>End of Transmission</td>
                        <td></td>
                        <td>36</td>
                        <td>24</td>
                        <td>&#36;</td>
                        <td></td>
                        <td>68</td>
                        <td>44</td>
                        <td>D</td>
                        <td></td>
                        <td>100</td>
                        <td>64</td>
                        <td>d</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>05</td>
                        <td>ENQ</td>
                        <td>CTRL-E</td>
                        <td>Enquiry</td>
                        <td></td>
                        <td>37</td>
                        <td>25</td>
                        <td>&#37;</td>
                        <td></td>
                        <td>69</td>
                        <td>45</td>
                        <td>E</td>
                        <td></td>
                        <td>101</td>
                        <td>65</td>
                        <td>e</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>06</td>
                        <td>ACK</td>
                        <td>CTRL-F</td>
                        <td>Acknowledge</td>
                        <td></td>
                        <td>38</td>
                        <td>26</td>
                        <td>&amp;</td>
                        <td></td>
                        <td>70</td>
                        <td>46</td>
                        <td>F</td>
                        <td></td>
                        <td>102</td>
                        <td>66</td>
                        <td>f</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>07</td>
                        <td>BEL</td>
                        <td>CTRL-G</td>
                        <td>Bell, Alert</td>
                        <td></td>
                        <td>39</td>
                        <td>27</td>
                        <td>&#39;</td>
                        <td></td>
                        <td>71</td>
                        <td>47</td>
                        <td>G</td>
                        <td></td>
                        <td>103</td>
                        <td>67</td>
                        <td>g</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>08</td>
                        <td>BS</td>
                        <td>CTRL-H</td>
                        <td>Backspace</td>
                        <td></td>
                        <td>40</td>
                        <td>28</td>
                        <td>&#40;</td>
                        <td></td>
                        <td>72</td>
                        <td>48</td>
                        <td>H</td>
                        <td></td>
                        <td>104</td>
                        <td>68</td>
                        <td>h</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>09</td>
                        <td>HT</td>
                        <td>CTRL-I</td>
                        <td>Horizontal Tab</td>
                        <td></td>
                        <td>41</td>
                        <td>29</td>
                        <td>&#41;</td>
                        <td></td>
                        <td>73</td>
                        <td>49</td>
                        <td>I</td>
                        <td></td>
                        <td>105</td>
                        <td>69</td>
                        <td>i</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>0A</td>
                        <td>LF</td>
                        <td>CTRL-J</td>
                        <td>Line Feed</td>
                        <td></td>
                        <td>42</td>
                        <td>2A</td>
                        <td>&#42;</td>
                        <td></td>
                        <td>74</td>
                        <td>4A</td>
                        <td>J</td>
                        <td></td>
                        <td>106</td>
                        <td>6A</td>
                        <td>j</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>0B</td>
                        <td>VT</td>
                        <td>CTRL-K</td>
                        <td>Vertical Tabulation</td>
                        <td></td>
                        <td>43</td>
                        <td>2B</td>
                        <td>&#43;</td>
                        <td></td>
                        <td>75</td>
                        <td>4B</td>
                        <td>K</td>
                        <td></td>
                        <td>107</td>
                        <td>6B</td>
                        <td>k</td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>0C</td>
                        <td>FF</td>
                        <td>CTRL-L</td>
                        <td>Form Feed</td>
                        <td></td>
                        <td>44</td>
                        <td>2C</td>
                        <td>&#44;</td>
                        <td></td>
                        <td>76</td>
                        <td>4C</td>
                        <td>L</td>
                        <td></td>
                        <td>108</td>
                        <td>6C</td>
                        <td>l</td>
                    </tr>
                    <tr>
                        <td>13</td>
                        <td>0D</td>
                        <td>CR</td>
                        <td>CTRL-M</td>
                        <td>Carriage Return</td>
                        <td></td>
                        <td>45</td>
                        <td>2D</td>
                        <td>&#45;</td>
                        <td></td>
                        <td>77</td>
                        <td>4D</td>
                        <td>M</td>
                        <td></td>
                        <td>109</td>
                        <td>6D</td>
                        <td>m</td>
                    </tr>
                    <tr>
                        <td>14</td>
                        <td>0E</td>
                        <td>SO</td>
                        <td>CTRL-N</td>
                        <td>Shift Out</td>
                        <td></td>
                        <td>46</td>
                        <td>2E</td>
                        <td>&#46;</td>
                        <td></td>
                        <td>78</td>
                        <td>4E</td>
                        <td>N</td>
                        <td></td>
                        <td>110</td>
                        <td>6E</td>
                        <td>n</td>
                    </tr>
                    <tr>
                        <td>15</td>
                        <td>0F</td>
                        <td>SI</td>
                        <td>CTRL-O</td>
                        <td>Shift In</td>
                        <td></td>
                        <td>47</td>
                        <td>2F</td>
                        <td>&#47;</td>
                        <td></td>
                        <td>79</td>
                        <td>4F</td>
                        <td>O</td>
                        <td></td>
                        <td>111</td>
                        <td>6F</td>
                        <td>o</td>
                    </tr>
                    <tr>
                        <td>16</td>
                        <td>10</td>
                        <td>DLE</td>
                        <td>CTRL-P</td>
                        <td>Data Link Escape</td>
                        <td></td>
                        <td>48</td>
                        <td>30</td>
                        <td>0</td>
                        <td></td>
                        <td>80</td>
                        <td>50</td>
                        <td>P</td>
                        <td></td>
                        <td>112</td>
                        <td>70</td>
                        <td>p</td>
                    </tr>
                    <tr>
                        <td>17</td>
                        <td>11</td>
                        <td>DC1</td>
                        <td>CTRL-Q</td>
                        <td>Device Control One (XON)</td>
                        <td></td>
                        <td>49</td>
                        <td>31</td>
                        <td>1</td>
                        <td></td>
                        <td>81</td>
                        <td>51</td>
                        <td>Q</td>
                        <td></td>
                        <td>113</td>
                        <td>71</td>
                        <td>q</td>
                    </tr>
                    <tr>
                        <td>18</td>
                        <td>12</td>
                        <td>DC2</td>
                        <td>CTRL-R</td>
                        <td>Device Control Two</td>
                        <td></td>
                        <td>50</td>
                        <td>32</td>
                        <td>2</td>
                        <td></td>
                        <td>82</td>
                        <td>52</td>
                        <td>R</td>
                        <td></td>
                        <td>114</td>
                        <td>72</td>
                        <td>r</td>
                    </tr>
                    <tr>
                        <td>19</td>
                        <td>13</td>
                        <td>DC3</td>
                        <td>CTRL-S</td>
                        <td>Device Control Three (XOFF)</td>
                        <td></td>
                        <td>51</td>
                        <td>33</td>
                        <td>3</td>
                        <td></td>
                        <td>83</td>
                        <td>53</td>
                        <td>S</td>
                        <td></td>
                        <td>115</td>
                        <td>73</td>
                        <td>s</td>
                    </tr>
                    <tr>
                        <td>20</td>
                        <td>14</td>
                        <td>DC4</td>
                        <td>CTRL-T</td>
                        <td>Device Control Four</td>
                        <td></td>
                        <td>52</td>
                        <td>34</td>
                        <td>4</td>
                        <td></td>
                        <td>84</td>
                        <td>54</td>
                        <td>T</td>
                        <td></td>
                        <td>116</td>
                        <td>74</td>
                        <td>t</td>
                    </tr>
                    <tr>
                        <td>21</td>
                        <td>15</td>
                        <td>NAK</td>
                        <td>CTRL-U</td>
                        <td>Negative Acknowledge</td>
                        <td></td>
                        <td>53</td>
                        <td>35</td>
                        <td>5</td>
                        <td></td>
                        <td>85</td>
                        <td>55</td>
                        <td>U</td>
                        <td></td>
                        <td>117</td>
                        <td>75</td>
                        <td>u</td>
                    </tr>
                    <tr>
                        <td>22</td>
                        <td>16</td>
                        <td>SYN</td>
                        <td>CTRL-V</td>
                        <td>Synchronous Idle</td>
                        <td></td>
                        <td>54</td>
                        <td>36</td>
                        <td>6</td>
                        <td></td>
                        <td>86</td>
                        <td>56</td>
                        <td>V</td>
                        <td></td>
                        <td>118</td>
                        <td>76</td>
                        <td>v</td>
                    </tr>
                    <tr>
                        <td>23</td>
                        <td>17</td>
                        <td>ETB</td>
                        <td>CTRL-W</td>
                        <td>End of Transmission Block</td>
                        <td></td>
                        <td>55</td>
                        <td>37</td>
                        <td>7</td>
                        <td></td>
                        <td>87</td>
                        <td>57</td>
                        <td>W</td>
                        <td></td>
                        <td>119</td>
                        <td>77</td>
                        <td>w</td>
                    </tr>
                    <tr>
                        <td>24</td>
                        <td>18</td>
                        <td>CAN</td>
                        <td>CTRL-X</td>
                        <td>Cancel</td>
                        <td></td>
                        <td>56</td>
                        <td>38</td>
                        <td>8</td>
                        <td></td>
                        <td>88</td>
                        <td>58</td>
                        <td>X</td>
                        <td></td>
                        <td>120</td>
                        <td>78</td>
                        <td>x</td>
                    </tr>
                    <tr>
                        <td>25</td>
                        <td>19</td>
                        <td>EM</td>
                        <td>CTRL-Y</td>
                        <td>End of medium</td>
                        <td></td>
                        <td>57</td>
                        <td>39</td>
                        <td>9</td>
                        <td></td>
                        <td>89</td>
                        <td>59</td>
                        <td>Y</td>
                        <td></td>
                        <td>121</td>
                        <td>79</td>
                        <td>y</td>
                    </tr>
                    <tr>
                        <td>26</td>
                        <td>1A</td>
                        <td>SUB</td>
                        <td>CTRL-Z</td>
                        <td>Substitute</td>
                        <td></td>
                        <td>58</td>
                        <td>3A</td>
                        <td>&#58;</td>
                        <td></td>
                        <td>90</td>
                        <td>5A</td>
                        <td>Z</td>
                        <td></td>
                        <td>122</td>
                        <td>7A</td>
                        <td>z</td>
                    </tr>
                    <tr>
                        <td>27</td>
                        <td>1B</td>
                        <td>ESC</td>
                        <td>CTRL-&#91;</td>
                        <td>Escape</td>
                        <td></td>
                        <td>59</td>
                        <td>3B</td>
                        <td>&#59;</td>
                        <td></td>
                        <td>91</td>
                        <td>5B</td>
                        <td>&#91;</td>
                        <td></td>
                        <td>123</td>
                        <td>7B</td>
                        <td>&#123;</td>
                    </tr>
                    <tr>
                        <td>28</td>
                        <td>1C</td>
                        <td>FS</td>
                        <td>CTRL-&#92;</td>
                        <td>File Separator</td>
                        <td></td>
                        <td>60</td>
                        <td>3C</td>
                        <td>&lt;</td>
                        <td></td>
                        <td>92</td>
                        <td>5C</td>
                        <td>&#92;</td>
                        <td></td>
                        <td>124</td>
                        <td>7C</td>
                        <td>&#124;</td>
                    </tr>
                    <tr>
                        <td>29</td>
                        <td>1D</td>
                        <td>GS</td>
                        <td>CTRL-&#93;</td>
                        <td>Group Separator</td>
                        <td></td>
                        <td>61</td>
                        <td>3D</td>
                        <td>&#61;</td>
                        <td></td>
                        <td>93</td>
                        <td>5D</td>
                        <td>&#93;</td>
                        <td></td>
                        <td>125</td>
                        <td>7D</td>
                        <td>&#125;</td>
                    </tr>
                    <tr>
                        <td>30</td>
                        <td>1E</td>
                        <td>RS</td>
                        <td>CTRL-&#94;</td>
                        <td>Record Separator</td>
                        <td></td>
                        <td>62</td>
                        <td>3E</td>
                        <td>&gt;</td>
                        <td></td>
                        <td>94</td>
                        <td>5E</td>
                        <td>&#94;</td>
                        <td></td>
                        <td>126</td>
                        <td>7E</td>
                        <td>&#126;</td>
                    </tr>
                    <tr>
                        <td>31</td>
                        <td>1F</td>
                        <td>US</td>
                        <td>CTRL-&#95;</td>
                        <td>Unit Separator</td>
                        <td></td>
                        <td>63</td>
                        <td>3F</td>
                        <td>&#63;</td>
                        <td></td>
                        <td>95</td>
                        <td>5F</td>
                        <td>&#95;</td>
                        <td></td>
                        <td>127</td>
                        <td>7F</td>
                        <td>DEL</td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
}
